# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='college',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='family',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='growth_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='growth_3',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='growth_5',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='list_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='price_to_rent',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='price_to_rent_est_beds',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='price_to_rent_est_sqft',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyType',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_estimate_beds',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_estimate_sqft',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='unemployed',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='vacancy',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.IntegerField(choices=[(1, 'House'), (2, 'Townhouse'), (3, 'Apartment'), (4, 'Studio')], default=1),
        ),
    ]
