# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190928_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='on_market',
            field=models.IntegerField(default=0),
        ),
    ]
