# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_property_on_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='zoning',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
