# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_property_zoning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantor', models.CharField(max_length=1000, null=True)),
                ('grantee', models.CharField(max_length=1000, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('order', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='parcel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='parcel',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='realty.Property'),
        ),
    ]
