# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-29 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190929_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='parcel',
            new_name='property',
        ),
    ]
