# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20190929_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parcel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
