# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_transaction_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='property',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='realty.Property'),
        ),
    ]
