# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_auto_20191005_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parcel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parcel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
