# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-05 19:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0013_auto_20191005_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='transactions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
