# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0014_auto_20191005_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='centralair',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
