# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0016_auto_20191008_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
