# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0017_auto_20191020_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parcel',
            field=models.BigIntegerField(null=True),
        ),
    ]
