# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-20 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0018_auto_20191020_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='on_market',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'SFH'), (3, 'Condo'), (4, 'Duplex'), (5, 'Triplex'), (6, 'Quadruplex'), (7, '5+ Units')], default=1),
        ),
    ]
