# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0019_auto_20191020_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
