# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0020_auto_20191027_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='units',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
