# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0021_property_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.FloatField(null=True),
        ),
    ]
