# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0024_auto_20191102_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='nb_type',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='new_build',
            field=models.IntegerField(null=True),
        ),
    ]
