# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0025_auto_20191103_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='list_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='original_price',
            field=models.FloatField(null=True),
        ),
    ]
