# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0028_auto_20191124_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='abseentee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='vacant',
            field=models.IntegerField(null=True),
        ),
    ]
