# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-24 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0029_auto_20191124_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='abseentee',
            new_name='absentee',
        ),
    ]
