# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-14 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0030_auto_20191124_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='college',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='growth_1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='growth_3',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='growth_5',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='list_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_to_rent_est_beds',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_to_rent_est_sqft',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_estimate_beds',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_estimate_sqft',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='unemployed',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='vacancy',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
