# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-14 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0032_auto_20200614_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_to_rent',
            field=models.FloatField(default=None, max_length=250, null=True),
        ),
    ]
